about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about_us, name = 'about_us'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name = 'post_list'),
    path('<int:id>', views.post_detail, name = 'post_detail'),
    path('tags=<slug:tag>', views.post_by_tag , name = 'post_by_tag'),
    path('category=<slug:category>', views.post_by_category , name = 'post_by_category'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_v, name = 'home_v'),
]

pricing/urls.py
from django.urls import path
from . import views

app_name = 'pricing'

urlpatterns = [
    path('', views.pricing_us, name = 'pricing_us'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace = 'home')),
    path('service/',include('service.urls',namespace = 'service')),
    path('blog/',include('blog.urls',namespace = 'blog')),
    path('pricing/',include('pricing.urls',namespace = 'pricing')),
    path('aboutus/',include('about.urls',namespace = 'about')),
]

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from . import views

app_name = 'service'

urlpatterns = [
    path('', views.service_us, name = 'service_us'),
]

about/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
	user = models.OneToOneField(User,on_delete = models.CASCADE)
	phon_number = models.CharField(max_length=20)
	p_image = models.ImageField(upload_to = 'media/profile')
	work_type = models.CharField(max_length=50)

	def __str__(self):
		return str(self.user)
	

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
	if created:
		Profile.objects.create(user=instance)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from slugify import slugify
from taggit.managers import TaggableManager

class BlogPost(models.Model):
	auther = models.ForeignKey(User,on_delete=models.CASCADE)
	title = models.CharField(max_length=150)
	description = models.TextField()
	image = models.ImageField(upload_to = 'media/blog')
	created = models.DateTimeField(default=timezone.now)
	category = models.ForeignKey('Category',on_delete = models.SET_NULL,null=True)
	tags = TaggableManager(blank=True)




	def __str__(self):
		return str(self.title)



	class Meta:
		verbose_name='BlogPostss'
		verbose_name_plural='BlogPosts'




class Category(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

SCHELDULE_TYPE =(
		('9 AM to 10 AM','9 AM to 10 AM'),
		('11 AM to 12 AM','11 AM to 12 AM'),
		('2 PM to 4 PM','2 PM to 4 PM'),
		('8 PM to 10 PM','8 PM to 10 PM'),
	)

class Apointment(models.Model):
	name = models.CharField(max_length=50)
	phone = models.CharField(max_length=50)
	addresse = models.CharField(max_length=50)
	scheldule = models.CharField(max_length=50,choices=SCHELDULE_TYPE)


	def __str__(self):
		return self.name

	class Meta:
		verbose_name='apointment'
		verbose_name_plural='apointments'

pricing/models.py
from django.db import models

class Price(models.Model):
	title = models.CharField(max_length=50)
	stage = models.CharField(max_length=25)
	price = models.IntegerField()

	def __str__(self):
 		return self.title

service/models.py
from django.db import models


class Service(models.Model):
	image = models.ImageField(upload_to = 'media/service')
	title = models.CharField(max_length=50)
	text = models.TextField()

	def __str__(self):
		return self.title

home/forms.py
from django import forms
from .models import Apointment


class ApointmentForm(forms.ModelForm):
	class Meta:
		model = Apointment
		fields = '__all__'

about/views.py
from django.shortcuts import render
from .models import Profile
# Create your views here.
def about_us(request):
	profile = Profile.objects.all()
	context = {'profile':profile,}
	return render(request,'about/aboutus.html',context) 

blog/views.py
from django.shortcuts import render
from .models import BlogPost, Category
from django.core.paginator import Paginator
from django.utils import timezone
from taggit.models import Tag
from django.db.models import Q


def post_list(request):
	post_list = BlogPost.objects.all()
	latests = BlogPost.objects.filter(created__lte=timezone.now()).reverse()[:3]
	categories = Category.objects.all()
	search_query = request.GET.get('q')
	if search_query:
		post_list = post_list.filter(
			Q(title__icontains = search_query)|
			Q(description__icontains = search_query)|
			Q(tags__name__icontains = search_query)
			).distinct()
	paginator = Paginator(post_list, 2)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)	

	context = {
			'post_list':page_obj,
			'categories':categories,
			'latests':latests,
			}
	return render(request,'blog/blog.html',context)

def post_detail(request,id):
	blog_detail = BlogPost.objects.get(id=id)
	latests = BlogPost.objects.filter(created__lte=timezone.now()).reverse()[:3]
	categories = Category.objects.all()
	all_tags = Tag.objects.all()
	context = {
					'blog_detail':blog_detail,
					'categories':categories,
					'latests':latests,
					'all_tags':all_tags,
				}
	return render(request,'blog/blog_detail.html',context)

def post_by_tag(request,tag):

	post_by_tag = BlogPost.objects.filter(tags__name__in=[tag])
	context = {
			'post_list':post_by_tag,
			}
	return render(request,'blog/blog.html',context)


def post_by_category(request,category):
	post_by_category = BlogPost.objects.filter(category__name=category)
	context = {
			'post_list':post_by_category,
			}
	return render(request,'blog/blog.html',context)

contact/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render,redirect
from service.models import Service
from pricing.models import Price
from about.models import Profile
from blog.models import BlogPost 
from .forms import ApointmentForm

def home_v(request):
	services = Service.objects.all()
	pricess = Price.objects.all()
	profiles = Profile.objects.all()
	post_list = BlogPost.objects.all()

	if request.method == 'POST':
		form = ApointmentForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/')
	else:
		form = ApointmentForm()
	context = {
				'services':services,
				'pricess':pricess,
				'profiles':profiles,
				'post_list':post_list,
				'form':form,
				}
	return render(request,'home/index.html',context)

pricing/views.py
from django.shortcuts import render
from .models import Price
def pricing_us(request):
	prices = Price.objects.all()
	context = {'prices':prices,}
	return render(request,'pricing/price.html',context)

service/views.py
from django.shortcuts import render
from .models import Service
from blog.models import BlogPost

def service_us(request):
	services = Service.objects.all()
	post_list = BlogPost.objects.all()
	context = {'services':services,
				'post_list':post_list,
				}
	return render(request,'service/services.html',context)

about/templates/about/aboutus.html
{% extends "base.html" %}
{% load static %}
{% block body %}
   


  <div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'img/bg-img/12.jpg' %});">
        <div class="container h-100">
          <div class="row h-100 align-items-center">
            <div class="col-12">
              <h2 class="title">About Us</h2>
            </div>
          </div>
        </div>
  </div>
  <div class="breadcumb--con">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">About Us</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ****** About Us Area Start ******* -->
  <section class="dento-about-us-area mt-70">
    <div class="container">
      <div class="row align-items-center">
        <!-- About Us Thumbnail -->
        <div class="col-12 col-md-6">
          <div class="about-us-thumbnail mb-50">
            <img src="{% static 'img/bg-img/15.jpg' %}" alt="">
          </div>
        </div>
        <!-- About Content -->
        <div class="col-12 col-md-6">
          <div class="about-us-content mb-50">
            <!-- Section Heading -->
            <div class="section-heading">
              <h2>About Us</h2>
              <div class="line"></div>
            </div>
            <p>Vestibulum condimentum, risus sedones honcus rutrum, salah lacus mollis zurna, nec finibusmi velit advertisis. Proin vitae odin quis magna aliquet laciniae. Etiam auctor, nisi vel. Pellentesque ultrices nisl quam iaculis, nec pulvinar
              augue.</p>

            <!-- Single Skills Area -->
            <div class="single-skills-area mt-30">
              <h6>Experience Dentist</h6>
              <div id="bar1" class="barfiller">
                <span class="tip"></span>
                <span class="fill" data-percentage="80"></span>
              </div>
            </div>

            <!-- Single Skills Area -->
            <div class="single-skills-area mt-30">
              <h6>Modern Equipment</h6>
              <div id="bar2" class="barfiller">
                <span class="tip"></span>
                <span class="fill" data-percentage="65"></span>
              </div>
            </div>

            <!-- Single Skills Area -->
            <div class="single-skills-area mt-30">
              <h6>Friendly Staff</h6>
              <div id="bar3" class="barfiller">
                <span class="tip"></span>
                <span class="fill" data-percentage="85"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ****** About Us Area End ****** -->

  <div class="container">
    <div class="dento-border clearfix"></div>
  </div>

  <!-- Cool Facts Area Start -->
  <section class="dento-cta-area">
    <div class="container">
      <div class="row">
        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_genius"></i>
            <h2><span class="counter">20</span></h2>
            <h5>Years Of Experience</h5>
          </div>
        </div>

        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_heart_alt"></i>
            <h2><span class="counter">700</span>+</h2>
            <h5>Happy Patients</h5>
          </div>
        </div>

        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_book_alt"></i>
            <h2><span class="counter">120</span></h2>
            <h5>Certificate</h5>
          </div>
        </div>

        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_id"></i>
            <h2><span class="counter">40</span>+</h2>
            <h5>Dentist</h5>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Cool Facts Area End -->

  <!-- ***** Testimonials Area Start ***** -->

  <!-- ***** Testimonials Area End ***** -->

  <!-- ***** Dento Dentist Area Start ***** -->
  <section class="dentist-area section-padding-100-0">
    <div class="container">
      <div class="row">
        <!-- Section Heading -->
        <div class="col-12">
          <div class="section-heading text-center">
            <h2>Our Dentist</h2>
            <div class="line"></div>
          </div>
        </div>
      </div>

      <div class="row">
        {% for i in profile %}
          
        
            <div class="col-12 col-sm-6 col-md-4">
              <div class="single-dentist-area mb-100">
                <img src="{{i.p_image.url}}" alt="">
                <!-- Dentist Content -->
                <div class="dentist-content">
                  <!-- Social Info -->
                  <div class="dentist-social-info">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-google-plus"></i></a>
                  </div>
                  <!-- Dentist Info -->
                  <div class="dentist-info bg-gradient-overlay">
                    <h5>{{i.user.username}}</h5>
                    <p>{{i.work_type}}</p>
                  </div>
                </div>
              </div>
            </div>

        {% endfor %}

      </div>
    </div>
  </section>
  <!-- ***** Dento Dentist Area End ***** -->
 {% endblock body %} 

blog/templates/blog/blog.html
{% extends "base.html" %}
{% load static %}
{% block body %}
	
  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'img/bg-img/12.jpg' %});">
	    <div class="container h-100">
	      <div class="row h-100 align-items-center">
	        <div class="col-12">
	          <h2 class="title">Blog</h2>
	        </div>
	      </div>
	    </div>
  </div>
  <div class="breadcumb--con">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Blog</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>

  <!-- *****Blog Area Start ***** -->
  <section class="dento-blog-area mt-50">
    <div class="container">
      <div class="row">
        <div class="col-12 col-lg-8">

         {% for post in post_list %}
	          <div class="single-blog-item style-2 d-flex flex-wrap align-items-center mb-50">
	       
			            <div class="blog-thumbnail">
			              <a href="{% url 'blog:post_detail' post.id %}">
			                <img src="{{post.image.url}}" alt="">
			              </a>
			            </div>
			            <!-- Blog Content -->
			            <div class="blog-content">
			              <a href="{% url 'blog:post_detail' post.id %}" class="post-title">{{post.title}}</a>
			              <p>{{post.description|truncatewords:50 }}</p>
			              <div class="post-meta">
			                <a href="#"><i class="icon_clock_alt"></i>{{post.created|date:'j M o'}}</a>
			                
			              </div>
			            </div>
	          </div>

         {% endfor %}
          
          {% if post_list.has_other_pages %}
		          <nav class="dento-pagination mb-100">
		            <ul class="pagination">
		            	{% if post_list.has_previous %}                
		             			 <li class="page-item"><a class="page-link" href="?page={{post_list.previous_page_number}}"><i class="fa fa-angle-left"></i></a></li>
		             	{% endif %}

		            	{% for i in post_list.paginator.page_range %}
				              <li class="page-item "><a class="page-link" href="?page={{i}}">{{i}}</a></li>
				        {% endfor %}
                        
                        {% if post_list.has_next %}                
		             			 <li class="page-item"><a class="page-link" href="?page={{post_list.next_page_number}}"><i class="fa fa-angle-right"></i></a></li>
		             	{% endif %}
		            </ul>
		          </nav>
		   {% endif %}
        </div>

        <!-- Dento Sidebar Area -->
        <div class="col-12 col-lg-4">
          <div class="dento-sidebar">

            <!-- Single Widget Area -->
            <div class="single-widget-area search-widget">
               <form method="GET" action="{% url 'blog:post_list' %}">
            
                <input type="search" name="q" class="form-control" placeholder="Search ..." value="{{request.Get.q}}">
                <button type="submit"><i class="icon_search"></i></button>
              </form>
            </div>

            <!-- Single Widget Area -->
            <div class="single-widget-area catagories-widget">
              <h5 class="widget-title">Categories</h5>

              <!-- catagories list -->
              <ul class="catagories-list">
	              	{% for cat in categories  %}
	               		 <li><a href="{% url 'blog:post_by_category' cat %}">{{cat}}</a></li>
	                {% endfor %}
              </ul>
            </div>

            <!-- Single Widget Area -->
            <div class="single-widget-area news-widget">
              <h5 class="widget-title">Recent News</h5>

              <!-- Single News Area -->
               {% for po in latests  %}
     
	              <div class="single-news-area d-flex align-items-center">
			                <div class="blog-thumbnail">
			                  <img src="{{po.image.url}}" alt="">
			                </div>
			                <div class="blog-content">
			                  <a href="{% url 'blog:post_detail' po.id %}" class="post-title">{{po.title}}</a>
			                  <span class="post-date">{{po.created|date:'j M o'}}</span>
			                </div>
	              </div>


              {% endfor %}

              <!-- Single News Area -->
          
            <!-- Single Widget Area -->
        

          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- *****Blog Area End ***** -->
{% endblock body %}

blog/templates/blog/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% block body %}
	  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'img/bg-img/12.jpg' %});">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">
          <h2 class="title">Blog Details</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="breadcumb--con">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Blog Details</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->
  	  	<div class="container">
			  <div class="mt-5">
			  	{% for tag in blog_detail.tags.all %}

			  		<a href="{% url 'blog:post_by_tag' tag %}" class="tag tag_color1">{{tag.name}}</a>

			  	{% endfor %}
			  </div>
	</div>
  <!-- ****** Blog Area Start ******* -->
  <section class="dento--blog-area mt-50">
    <div class="container">
      <div class="row">
        <div class="col-12 col-lg-8 mb-100">
          <!-- Blog Details Area -->
          <div class="blog-details-area">
            <img src="{{blog_detail.image.url}}" alt="">

            <h2 class="post-title">{{blog_detail.title}}</h2>
            <div class="post-meta">
              <a href="#"><i class="icon_clock_alt"></i>{{blog_detail.created|date:'j M o'}}</a>
              
            </div>
            {{blog_detail.description}}
          </div>

          <!-- Post Share  -->
          <div class="post-share-area mb-30">
            <a href="#" class="facebook"><i class="fa fa-facebook"></i> Share</a>
            <a href="#" class="tweet"><i class="fa fa-twitter"></i> Tweet</a>
            <a href="#" class="google-plus"><i class="fa fa-google-plus"></i> Share</a>
            <a href="#" class="pinterest"><i class="fa fa-pinterest"></i> Share</a>
          </div>

          <!-- Comments Area -->
          <div class="comment_area clearfix">
            <h5 class="title">3 Comments</h5>

            <ol>
              <!-- Single Comment Area -->
              <li class="single_comment_area">
                <!-- Comment Content -->
                <div class="comment-content d-flex">
                  <!-- Comment Author -->
                  <div class="comment-author">
                    <img src="img/bg-img/26.jpg" alt="author">
                  </div>
                  <!-- Comment Meta -->
                  <div class="comment-meta">
                    <a href="#" class="post-author">Tom Hardy / <span>28 Sep 2018 at 10:00 am</span></a>
                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sitdown ameto, consectetur, adipisci velit, sed quiata non numqua eius modi tempor incidunt ut labore.</p>
                    <a href="#" class="comment-reply">Reply</a>
                  </div>
                </div>
                <ol class="children">
                  <li class="single_comment_area">
                    <!-- Comment Content -->
                    <div class="comment-content d-flex">
                      <!-- Comment Author -->
                      <div class="comment-author">
                        <img src="img/bg-img/27.jpg" alt="author">
                      </div>
                      <!-- Comment Meta -->
                      <div class="comment-meta">
                        <a href="#" class="post-author">Samantha Harvey / <span>28 Sep 2018 at 10:30 am</span></a>
                        <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sitdown ameto, consectetur, adipisci velit, sed quiata non numqua eius modi tempor incidunt ut labore.</p>
                        <a href="#" class="comment-reply">Reply</a>
                      </div>
                    </div>
                  </li>
                </ol>
              </li>

              <!-- Single Comment Area -->
              <li class="single_comment_area">
                <!-- Comment Content -->
                <div class="comment-content d-flex">
                  <!-- Comment Author -->
                  <div class="comment-author">
                    <img src="img/bg-img/28.jpg" alt="author">
                  </div>
                  <!-- Comment Meta -->
                  <div class="comment-meta">
                    <a href="#" class="post-author">Jonny Evans / <span>28 Sep 2018 at 11:00 am</span></a>
                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sitdown ameto, consectetur, adipisci velit, sed quiata non numqua eius modi tempor incidunt ut labore.</p>
                    <a href="#" class="comment-reply">Reply</a>
                  </div>
                </div>
              </li>
            </ol>
          </div>

          <!-- Leave A Reply -->
          <div class="contact-form mt-30">
            <h5 class="mb-30">Leave A Reply</h5>

            <!-- Form -->
            <form action="#" method="post">
              <div class="row">
                <div class="col-lg-6">
                  <input type="text" name="message-name" class="form-control mb-30" placeholder="Your Name">
                </div>
                <div class="col-lg-6">
                  <input type="email" name="message-email" class="form-control mb-30" placeholder="Your Email">
                </div>
                <div class="col-12">
                  <textarea name="message" class="form-control mb-30" placeholder="Your Message"></textarea>
                </div>
                <div class="col-12">
                  <button type="submit" class="btn dento-btn">Reply</button>
                </div>
              </div>
            </form>

          </div>
        </div>

        <!-- Dento Sidebar Area -->
        <div class="col-12 col-lg-4">
          <div class="dento-sidebar">

            <!-- Single Widget Area -->
            <div class="single-widget-area search-widget">
              <form method="GET" action="{% url 'blog:post_list' %}">
            
                <input type="search" name="q" class="form-control" placeholder="Search ..." value="{{request.Get.q}}">
                <button type="submit"><i class="icon_search"></i></button>
              </form>
            </div>

            <!-- Single Widget Area -->
            <div class="single-widget-area catagories-widget">
              <h5 class="widget-title">Categories</h5>

              <!-- catagories list -->
            
             	
            <ul class="catagories-list">
	              	{% for category in categories  %}
	               		 <li><a href="{% url 'blog:post_by_category' category %}">{{category}}</a></li>
	                {% endfor %}
              </ul>
              
            </div>

            <!-- Single Widget Area -->
            <div class="single-widget-area news-widget">
              <h5 class="widget-title">Recent News</h5>

              <!-- Single News Area -->
              {% for po in latests  %}
     
	              <div class="single-news-area d-flex align-items-center">
			                <div class="blog-thumbnail">
			                  <img src="{{po.image.url}}" alt="">
			                </div>
			                <div class="blog-content">
			                  <a href="{% url 'blog:post_detail' po.id %}" class="post-title">{{po.title}}</a>
			                  <span class="post-date">{{po.created|date:'j M o'}}</span>
			                </div>
	              </div>


              {% endfor %}
            </div>

            <!-- Single Widget Area -->
            <div class="single-widget-area adds-widget">
              <a href="#"><img class="w-100" src="./img/bg-img/adds.png" alt=""></a>
            </div>

          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ****** Blog Area End ******* -->

{% endblock body %}

service/templates/service/services.html
{% extends "base.html" %}
{% load static %}
{% block body %}
	  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'img/bg-img/12.jpg' %});">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">
          <h2 class="title">Service</h2>
        </div>
      </div>
    </div>
  </div>

  <div class="breadcumb--con">
	    <div class="container">
	      <div class="row">
	        <div class="col-12">
	          <nav aria-label="breadcrumb">
	            <ol class="breadcrumb">
	              <li class="breadcrumb-item"><a href=""><i class="fa fa-home"></i> Home</a></li>
	              <li class="breadcrumb-item active" aria-current="page">Service</li>
	            </ol>
	          </nav>
	        </div>
	      </div>
	    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ***** Services Area Start ***** -->
  <section class="dento-services-area mt-50 mb-50">
		    <div class="container">
		      <div class="row">

		        {% for service in services  %}
			        <div class="col-12 col-sm-6 col-lg-4">
			          <div class="single-service--area text-center mb-50">
			            <div class="icon--">
			              <img src="{{service.image.url}}" alt="">
			            </div>
			            <h5>{{service.title}}</h5>
			            <p>{{service.text}}.</p>
			          </div>
			        </div>      	
		        {% endfor %}
		      </div>
		    </div>
  </section>

  <section class="dento-blog-area section-padding-100-0 clearfix">
    <div class="container">
      <div class="row">
        <!-- Section Heading -->
        <div class="col-12">
          <div class="section-heading text-center">
            <h2>The Latest News</h2>
            <div class="line"></div>
          </div>
        </div>
      </div>

      <div class="row">
        <!-- Single Blog Item -->
                   {% for post in post_list %}

                <div class="col-12 col-md-6 col-lg-4">
                  <div class="single-blog-item mb-100">
                    <a href="{% url 'blog:post_detail' post.id %}">
                      <img src="{{post.image.url}}" alt="">
                    </a>
                    <!-- Blog Content -->
                    <div class="blog-content">
                      <a href="{% url 'blog:post_detail' post.id %}" class="post-title">{{post.title}}</a>
                      <p>{{post.description|truncatewords:20}}</p>
                      <div class="post-meta">
                        <a href="{% url 'blog:post_detail' post.id %}"><i class="icon_clock_alt"></i>{{post.created|date:'j M o'}}</a>
                        <a href="{% url 'blog:post_detail' post.id %}"><i class="icon_chat_alt"></i> 3 Comments</a>
                      </div>
                    </div>
                  </div>
                </div>

            {% endfor %}
      </div>
    </div>
  </section>
  <!-- ***** Blog Area End ***** -->
{% endblock body %}